added Azerbaijan language toml and wiki sample
common-voice/cv-sentence-extractor pull request #136
Opened 2021-04-11 22:23 UTC by damirci

How many sentences did you get at the end?
95031 lines on the output

How did you create the blacklist file?
I followed the instructions in the README, with a few changes:
I changed the word_usage.py to make it count words with Azerbaijan language Latin alphabet characters.
 ````   # Filter out symbols
    line = re.sub("[^A-z əöüğçşıİƏÖÜĞÇŞ]", " ", line)
 ````
Blocklist word frequency is 60 and lower.

Review

[random samples](https://github.com/damirci/cv-sentence-extractor/tree/main/samples)

2021-04-12 16:08 UTC, MichaelKohler requested changes
Thanks for your contribution. I've left a comment regarding the abbreviations.

I'm not sure I like the samples in the repository. I don't think we'll need those once this PR is merged. Once the review process is finished, would you mind removing those? And just a quick note: if it's easier for you, there is a Google Sheet template for reviews which makes the process a bit easier than just having text files: https://docs.google.com/spreadsheets/d/1dJpysfcwmUwR4oJuw5ttGcUFYLeTbmn50Fpufz9qx-8/edit#gid=0

2021-04-12 20:52 UTC, damirci commented on src/rules/az.toml
> +  "və s\\.|və i.a\\.|və b\\.|və b.k\\.|və.s\\.|və.i.a\\.|və.b\\.|e.ə\\.|e .ə\\.|E.ə\\.|E. ə\\.|ö\\.|m.ə\\.|  akad\\.|prof\\.|səh\\.|küç\\.|şəh\\.|qəs\\.|məs\\.|dok\\.|dos\\.|abrev\\.|adr\\.|km\\.|sm\
Thanks for comments, I applied the fixes

2021-04-14 02:06 UTC, damirci commented
I moved samples to google docs, and I fixed the az.toml file.

2021-04-17 14:56 UTC, MichaelKohler approved these changes
Thanks for the adjustments. I've left two minor comments. Could you also post the link to the Google Sheet for review?

2021-04-17 14:56 UTC, MichaelKohler commented on src/rules/az.toml
> +  "[A-ZİƏÖÜĞÇŞ]{2,}",
This should already be covered by the Regex above it?

2021-04-17 14:56 UTC, MichaelKohler commented on src/rules/az.toml
> +  # coommon abbr
-> common

2021-04-17 21:24 UTC, damirci commented
https://drive.google.com/drive/folders/1dzcVYhEyONPmsH6Mm4HhCG5nY1dcVz2f

2021-05-25 20:05 UTC, MichaelKohler approved these changes

2021-05-25 20:05 UTC, merged